# Generated by Django 4.2.1 on 2023-06-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_noticia_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
