# Generated by Django 4.2.1 on 2023-06-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('informacion', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='noticias')),
                ('estado', models.TextField(default='creado')),
                ('fecha_noticia', models.DateField()),
                ('periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.periodista')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.seccion')),
            ],
        ),
    ]
