# Generated by Django 4.2.1 on 2023-06-30 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_noticia_mensaje_rechazo_alter_noticia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 16, 54, 29, 770545)),
        ),
    ]
