# Generated by Django 4.2.1 on 2023-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_alter_noticia_fecha_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(null=True),
        ),
    ]
