# Generated by Django 4.2.1 on 2023-07-08 01:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_noticia_fecha_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='mensaje_rechazo',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
