# Generated by Django 4.2.1 on 2023-07-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_noticia_fecha2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha2',
        ),
    ]
