# Generated by Django 4.2.1 on 2023-07-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_remove_noticia_fecha2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
