# Generated by Django 4.2.1 on 2023-07-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_noticia_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('experiencia', models.TextField(null=True)),
                ('educacion', models.TextField(null=True)),
                ('foto', models.ImageField(null=True, upload_to='curriculums')),
            ],
        ),
    ]
